export const mockBankData = [
  {
    id: 'nubank',
    bankName: 'Nubank',
    bankColor: '#820AD1',
    accountType: 'checking',
    lastSync: null,
    status: 'disconnected',
    balance: 0,
  },
  {
    id: 'inter',
    bankName: 'Banco Inter',
    bankColor: '#FF7A00',
    accountType: 'checking',
    lastSync: null,
    status: 'disconnected',
    balance: 0,
  },
  {
    id: 'itau',
    bankName: 'Itaú',
    bankColor: '#003399',
    accountType: 'checking',
    lastSync: null,
    status: 'disconnected',
    balance: 0,
  },
  {
    id: 'bradesco',
    bankName: 'Bradesco',
    bankColor: '#CC092F',
    accountType: 'checking',
    lastSync: null,
    status: 'disconnected',
    balance: 0,
  },
  {
    id: 'bb',
    bankName: 'Banco do Brasil',
    bankColor: '#FFEF00',
    accountType: 'checking',
    lastSync: null,
    status: 'disconnected',
    balance: 0,
  },
  {
    id: 'caixa',
    bankName: 'Caixa',
    bankColor: '#005CA9',
    accountType: 'checking',
    lastSync: null,
    status: 'disconnected',
    balance: 0,
  },
  {
    id: 'c6',
    bankName: 'C6 Bank',
    bankColor: '#1A1A1A',
    accountType: 'checking',
    lastSync: null,
    status: 'disconnected',
    balance: 0,
  },
  {
    id: 'picpay',
    bankName: 'PicPay',
    bankColor: '#21C25E',
    accountType: 'checking',
    lastSync: null,
    status: 'disconnected',
    balance: 0,
  },
]

export const mockBankTransactions = [
  { id: 'bt1', description: 'PIX Recebido - João', amount: 350.00, type: 'income', date: '2026-04-22', category: 'other_income' },
  { id: 'bt2', description: 'Débito Automático - Netflix', amount: 55.90, type: 'expense', date: '2026-04-21', category: 'entertainment' },
  { id: 'bt3', description: 'Compra - iFood', amount: 45.50, type: 'expense', date: '2026-04-20', category: 'food' },
  { id: 'bt4', description: 'PIX Enviado - Aluguel', amount: 1500.00, type: 'expense', date: '2026-04-15', category: 'housing' },
  { id: 'bt5', description: 'Transferência Recebida - Salário', amount: 6500.00, type: 'income', date: '2026-04-05', category: 'salary' },
]
